### ISSUE TITLE
Allowing an array of plugins instead of objects

### ISSUE THREAD

**Issue by alexlafroscia** [jeffjewiss/broccoli-postcss#114]
I was wondering if there was a reason that this plugin doesn't support an array of plugins as well as the `modules/options` objects that it currently accepts.  For example, being able to specify this:

```js
{
  plugins: [
    require('autoprefixer')(options)
  ]
}
```

instead of the modules/options separately

```js
{
  plugins: [
    {
      module: require('autoprefixer'),
      options
    }
  ]
}
```

I ask because I'd like to be able to use this package within [`ember-css-modules`](https://github.com/salsify/ember-css-modules/pull/60), but would want to allow the `postprocess` plugins to use the same interface that the `before` and `after` plugins there do. I'm happy to make a PR if you're amenable to having both methods be supported.

Since I know that the options for each plugin are merged with some global options, I would propose that plugins handed their options directly would just opt out of this behavior altogether, which seems like reasonable behavior unless there's some reason that that can't be done.

**Comment by jeffjewiss** [comment]
I can't remember the specific reason that I set it up that way originally. I think it had to do with the timing of when plugins were initialized.

The merging of plugin options with global options is the main reason to have the plugin and it's options separate, but I believe there are only a few plugins that really take advantage of this. `autoprefixer` is an example since the browserlist config can be passed in when using this package as part of `ember-cli-postcss`.

I think your proposal is sound and would work well. If users of this plugin want to specify plugins with the array format and pass the options directly to the plugin function, then they'll need to manage the options themselves anyway.

If you have time to put together a PR I'd really appreciate it and I'm open to supporting both methods.

**Comment by alexlafroscia** [comment]
Sweet! I'll do that then. I have the test written for the method I suggested, but wanted to make sure you're cool with both methods before writing the code and asking you to support two methods.

**Comment by jeffjewiss** [comment]
Thanks for checking, sounds good!
