### ISSUE TITLE
Callbacks as plugins

### ISSUE THREAD

**Issue by alexlafroscia** [jeffjewiss/broccoli-postcss#116]
I have another request/proposal!

One thing that I've come across (rarely) is the need to configure a PostCSS plugin with information about the current directory of the files being operated on. Specifically, I've run into this with `postcss-sprites` and the need to locate the sprites themselves. Brococli makes this a bit tough, since you don't actually know where the files are on disk anymore.

We solves this issue by allowing a `plugin` to be a callback, that was threaded the output directory and the current file being processed. You can check out the code we've used [here](https://github.com/rondale-sc/ember-css-modules/blob/add-postprocess-plugin-set/lib/postcss-persistent-filter.js#L25-L29).

Would you be willing to consider a third type of plugin, a `callback`, in addition to the two methods supported here?  Again, I'll add the feature (and tests) if you're willing to accept a PR that added that feature.

Thanks!

**Comment by jeffjewiss** [comment]
Hey, sorry for the delay on this one.

I was trying to think about your use case a bit. I'm hesitant to add more types of plugins unless it's really necessary. I'm a little worried about the configuration becoming too tedious or error prone.

Regarding the example you gave, is `postcss-sprites` the only plugin where this has been an issue? Since `spritePath: './dist/images/'` is a relative path, and `{ from, to}` are passed to the plugin as options, is it possible to configure the plugin with that that info or is the use case more complicated and I'm missing something?

I was hoping that passing the relative path of the file to each plugin would be enough since this package is generally used in the postprocess step and `broccoli-postcss-single` is used as a main processor.

Let me know what you're thinking and we can likely work something out for this use case.

**Comment by alexlafroscia** [comment]
I was able to work around my issue -- not by using a relative path, but by just not doing sprites altogether 😝

**Comment by jeffjewiss** [comment]
Glad to hear you were able to find a work around! Thanks for following up on this issues. Cheers.
