### ISSUE TITLE
Running as a filter

### ISSUE THREAD

**Issue by myfreeweb** [jeffjewiss/broccoli-postcss#6]
Hi!

It would be great if this plugin had an option to run as a filter, applying postcss to every `.css` file in the input trees, without specifying `inputFile` / `outputFile`.

**Comment by jeffjewiss** [comment]
Hey, I agree, I think that's a great idea. I've been working on rewriting the plugin as a filter, but I have a couple of bugs to work out related to the postcss-import plugin before I can release it. I'll make sure to update this issue when I finish.

**Comment by epicmiller** [comment]
Hey @jeffjewiss, any update on this? This feature is required for our company to use this plugin. Would be happy to help if its not finished.

**Comment by jeffjewiss** [comment]
Hey @epicmiller, I did some exploratory work on this a little while ago here: https://github.com/jeffjewiss/broccoli-postcss/commits/filter

Unfortunately it's not finished and not at a state that it works with the current implementation. If you have time to work on this I'd really appreciate it. Let me know how I can help or lend support in any way.

**Comment by jeffjewiss** [comment]
Hey @epicmiller, I just pushed up an update to the `filter` branch. I have everything (except writing souremaps to a file) working and tests passing. Would you be able to test this out on your project by installing it with `jeffjewiss/broccoli-postcss#filter` as the package name in your package.json?

Other than working on all css files, the only other difference should be that the options are passed in as one object instead of separate arguments.

If you can confirm that this is working as a filter, I should be able to refactor the plugin to work as either a "compiler" or "filter". Please let me know if you think you'll have time this week to look into this. Thanks!

**Comment by epicmiller** [comment]
Hey Jeff, I should have the time to look into this a little later this week. Will let you know how it goes!

**Comment by chriseppstein** [comment]
@jeffjewiss @epicmiller https://github.com/jeffjewiss/broccoli-postcss/pull/12

**Comment by chriseppstein** [comment]
@jeffjewiss My branch PR uses your filter branch, but that was the code on friday. I then, I rebased against master and made all the tests pass.

**Comment by chriseppstein** [comment]
@jeffjewiss were your changes also just updating it to work against master?

**Comment by jeffjewiss** [comment]
@chriseppstein yeah, my changes were just to update it against master and to incorporate some updates I saw in the filter dependencies.

I left some notes in your PR for when you have a chance to take a look. :smile:

**Comment by jeffjewiss** [comment]
Hey @myfreeweb, I've rewritten the plugin as a filter and published 3.0. I know you submitted this a long time ago and have likely moved on, but I wanted to give you a heads up.

Cheers!

**Comment by myfreeweb** [comment]
Thank you!
